Hibernate: create table orders (total_amount float(53) not null, id bigint generated by default as identity, user_id bigint not null, primary key (id))
Hibernate: create table product_info (price float(53) not null, id bigint generated by default as identity, order_id bigint, name varchar(255) not null, primary key (id))
Hibernate: alter table if exists product_info add constraint FKpqkcjgr5uy3vddch4da20h07i foreign key (order_id) references orders



Hibernate: create table payment (id bigint generated by default as identity, order_id bigint not null, payment_method varchar(255) not null, payment_status varchar(255), primary key (id))